/*
 Platform.js <https://mths.be/platform>
 Copyright 2014-2018 Benjamin Tan <https://bnjmnt4n.now.sh/>
 Copyright 2011-2013 John-David Dalton
 Available under MIT license <https://mths.be/mit>
*/
(function(){function a(a){a=String(a);return a.charAt(0).toUpperCase()+a.slice(1)}function b(a,d){var k=-1,f=a?a.length:0;if("number"==typeof f&&-1<f&&f<=q)for(;++k<f;)d(a[k],k,a);else e(a,d)}function g(d){d=String(d).replace(/^ +| +$/g,"");return/^(?:webOS|i(?:OS|P))/.test(d)?d:a(d)}function e(a,d){for(var k in a)m.call(a,k)&&d(a[k],k,a)}function n(d){return null==d?a(d):A.call(d).slice(8,-1)}function h(a,d){var k=null!=a?typeof a[d]:"number";return!/^(?:boolean|number|string|undefined)$/.test(k)&&
("object"==k?!!a[d]:!0)}function r(a){return String(a).replace(/([ -])(?!$)/g,"$1?")}function p(a,d){var k=null;b(a,function(f,r){k=d(k,f,r,a)});return k}function l(a){function d(c){return p(c,function(c,d){var k=d.pattern||r(d);!c&&(c=RegExp("\\b"+k+" *\\d+[.\\w_]*","i").exec(a)||RegExp("\\b"+k+" *\\w+-[\\w]*","i").exec(a)||RegExp("\\b"+k+"(?:; *(?:[a-z]+[_-])?[a-z]+\\d+|[^ ();-]*)","i").exec(a))&&((c=String(d.label&&!RegExp(k,"i").test(d.label)?d.label:c).split("/"))[1]&&!/[\d.]+/.test(c[0])&&(c[0]+=
" "+c[1]),d=d.label||d,c=g(c[0].replace(RegExp(k,"i"),d).replace(RegExp("; *(?:"+d+"[_-])?","i")," ").replace(RegExp("("+d+")[-_.]?(\\w)","i"),"$1 $2")));return c})}function f(c){return p(c,function(c,d){return c||(RegExp(d+"(?:-[\\d.]+/|(?: for [\\w-]+)?[ /-])([\\d.]+[^ ();/_-]*)","i").exec(a)||0)[1]||null})}var b=k,q=a&&"object"==typeof a&&"String"!=n(a);q&&(b=a,a=null);var x=b.navigator||{},m=x.userAgent||"";a||(a=m);var I=q?!!x.likeChrome:/\bChrome\b/.test(a)&&!/internal|\n/i.test(A.toString()),
E=q?"Object":"ScriptBridgingProxyObject",z=q?"Object":"Environment",w=q&&b.java?"JavaPackage":n(b.java),T=q?"Object":"RuntimeObject";z=(w=/\bJava/.test(w)&&b.java)&&n(b.environment)==z;var y=w?"a":"\u03b1",N=w?"b":"\u03b2",Q=b.document||{},O=b.operamini||b.opera,J=t.test(J=q&&O?O["[[Class]]"]:n(O))?J:O=null,c,U=a;q=[];var V=null,P=a==m;m=P&&O&&"function"==typeof O.version&&O.version();var C=function(c){return p(c,function(c,d){return c||RegExp("\\b"+(d.pattern||r(d))+"\\b","i").exec(a)&&(d.label||
d)})}([{label:"EdgeHTML",pattern:"Edge"},"Trident",{label:"WebKit",pattern:"AppleWebKit"},"iCab","Presto","NetFront","Tasman","KHTML","Gecko"]),u=function(c){return p(c,function(c,d){return c||RegExp("\\b"+(d.pattern||r(d))+"\\b","i").exec(a)&&(d.label||d)})}(["Adobe AIR","Arora","Avant Browser","Breach","Camino","Electron","Epiphany","Fennec","Flock","Galeon","GreenBrowser","iCab","Iceweasel","K-Meleon","Konqueror","Lunascape","Maxthon",{label:"Microsoft Edge",pattern:"Edge"},"Midori","Nook Browser",
"PaleMoon","PhantomJS","Raven","Rekonq","RockMelt",{label:"Samsung Internet",pattern:"SamsungBrowser"},"SeaMonkey",{label:"Silk",pattern:"(?:Cloud9|Silk-Accelerated)"},"Sleipnir","SlimBrowser",{label:"SRWare Iron",pattern:"Iron"},"Sunrise","Swiftfox","Waterfox","WebPositive","Opera Mini",{label:"Opera Mini",pattern:"OPiOS"},"Opera",{label:"Opera",pattern:"OPR"},"Chrome",{label:"Chrome Mobile",pattern:"(?:CriOS|CrMo)"},{label:"Firefox",pattern:"(?:Firefox|Minefield)"},{label:"Firefox for iOS",pattern:"FxiOS"},
{label:"IE",pattern:"IEMobile"},{label:"IE",pattern:"MSIE"},"Safari"]),D=d([{label:"BlackBerry",pattern:"BB10"},"BlackBerry",{label:"Galaxy S",pattern:"GT-I9000"},{label:"Galaxy S2",pattern:"GT-I9100"},{label:"Galaxy S3",pattern:"GT-I9300"},{label:"Galaxy S4",pattern:"GT-I9500"},{label:"Galaxy S5",pattern:"SM-G900"},{label:"Galaxy S6",pattern:"SM-G920"},{label:"Galaxy S6 Edge",pattern:"SM-G925"},{label:"Galaxy S7",pattern:"SM-G930"},{label:"Galaxy S7 Edge",pattern:"SM-G935"},"Google TV","Lumia","iPad",
"iPod","iPhone","Kindle",{label:"Kindle Fire",pattern:"(?:Cloud9|Silk-Accelerated)"},"Nexus","Nook","PlayBook","PlayStation Vita","PlayStation","TouchPad","Transformer",{label:"Wii U",pattern:"WiiU"},"Wii","Xbox One",{label:"Xbox 360",pattern:"Xbox"},"Xoom"]),L=function(c){return p(c,function(c,d,k){return c||(d[D]||d[/^[a-z]+(?: +[a-z]+\b)*/i.exec(D)]||RegExp("\\b"+r(k)+"(?:\\b|\\w*\\d)","i").exec(a))&&k})}({Apple:{iPad:1,iPhone:1,iPod:1},Archos:{},Amazon:{Kindle:1,"Kindle Fire":1},Asus:{Transformer:1},
"Barnes & Noble":{Nook:1},BlackBerry:{PlayBook:1},Google:{"Google TV":1,Nexus:1},HP:{TouchPad:1},HTC:{},LG:{},Microsoft:{Xbox:1,"Xbox One":1},Motorola:{Xoom:1},Nintendo:{"Wii U":1,Wii:1},Nokia:{Lumia:1},Samsung:{"Galaxy S":1,"Galaxy S2":1,"Galaxy S3":1,"Galaxy S4":1},Sony:{PlayStation:1,"PlayStation Vita":1}}),v=function(c){return p(c,function(c,d){var k=d.pattern||r(d);if(!c&&(c=RegExp("\\b"+k+"(?:/[\\d.]+|[ \\w.]*)","i").exec(a))){var J=c,f=d.label||d,b={"10.0":"10","6.4":"10 Technical Preview",
"6.3":"8.1","6.2":"8","6.1":"Server 2008 R2 / 7","6.0":"Server 2008 / Vista","5.2":"Server 2003 / XP 64-bit","5.1":"XP","5.01":"2000 SP1","5.0":"2000","4.0":"NT","4.90":"ME"};k&&f&&/^Win/i.test(J)&&!/^Windows Phone /i.test(J)&&(b=b[/[\d.]+$/.exec(J)])&&(J="Windows "+b);J=String(J);k&&f&&(J=J.replace(RegExp(k,"i"),f));c=J=g(J.replace(/ ce$/i," CE").replace(/\bhpw/i,"web").replace(/\bMacintosh\b/,"Mac OS").replace(/_PowerPC\b/i," OS").replace(/\b(OS X) [^ \d]+/i,"$1").replace(/\bMac (OS X)\b/,"$1").replace(/\/(\d)/,
" $1").replace(/_/g,".").replace(/(?: BePC|[ .]*fc[ \d.]+)$/i,"").replace(/\bx86\.64\b/gi,"x86_64").replace(/\b(Windows Phone) OS\b/,"$1").replace(/\b(Chrome OS \w+) [\d.]+\b/,"$1").split(" on ")[0])}return c})}(["Windows Phone","Android","CentOS",{label:"Chrome OS",pattern:"CrOS"},"Debian","Fedora","FreeBSD","Gentoo","Haiku","Kubuntu","Linux Mint","OpenBSD","Red Hat","SuSE","Ubuntu","Xubuntu","Cygwin","Symbian OS","hpwOS","webOS ","webOS","Tablet OS","Tizen","Linux","Mac OS X","Macintosh","Mac",
"Windows 98;","Windows "]);C&&(C=[C]);L&&!D&&(D=d([L]));if(c=/\bGoogle TV\b/.exec(D))D=c[0];/\bSimulator\b/i.test(a)&&(D=(D?D+" ":"")+"Simulator");"Opera Mini"==u&&/\bOPiOS\b/.test(a)&&q.push("running in Turbo/Uncompressed mode");"IE"==u&&/\blike iPhone OS\b/.test(a)?(c=l(a.replace(/like iPhone OS/,"")),L=c.manufacturer,D=c.product):/^iP/.test(D)?(u||(u="Safari"),v="iOS"+((c=/ OS ([\d_]+)/i.exec(a))?" "+c[1].replace(/_/g,"."):"")):"Konqueror"!=u||/buntu/i.test(v)?L&&"Google"!=L&&(/Chrome/.test(u)&&
!/\bMobile Safari\b/i.test(a)||/\bVita\b/.test(D))||/\bAndroid\b/.test(v)&&/^Chrome/.test(u)&&/\bVersion\//i.test(a)?(u="Android Browser",v=/\bAndroid\b/.test(v)?v:"Android"):"Silk"==u?(/\bMobi/i.test(a)||(v="Android",q.unshift("desktop mode")),/Accelerated *= *true/i.test(a)&&q.unshift("accelerated")):"PaleMoon"==u&&(c=/\bFirefox\/([\d.]+)\b/.exec(a))?q.push("identifying as Firefox "+c[1]):"Firefox"==u&&(c=/\b(Mobile|Tablet|TV)\b/i.exec(a))?(v||(v="Firefox OS"),D||(D=c[1])):!u||(c=!/\bMinefield\b/i.test(a)&&
/\b(?:Firefox|Safari)\b/.exec(u))?(u&&!D&&/[\/,]|^[^(]+?\)/.test(a.slice(a.indexOf(c+"/")+8))&&(u=null),(c=D||L||v)&&(D||L||/\b(?:Android|Symbian OS|Tablet OS|webOS)\b/.test(v))&&(u=/[a-z]+(?: Hat)?/i.exec(/\bAndroid\b/.test(v)?v:c)+" Browser")):"Electron"==u&&(c=(/\bChrome\/([\d.]+)\b/.exec(a)||0)[1])&&q.push("Chromium "+c):v="Kubuntu";m||(m=f(["(?:Cloud9|CriOS|CrMo|Edge|FxiOS|IEMobile|Iron|Opera ?Mini|OPiOS|OPR|Raven|SamsungBrowser|Silk(?!/[\\d.]+$))","Version",r(u),"(?:Firefox|Minefield|NetFront)"]));
if(c="iCab"==C&&3<parseFloat(m)&&"WebKit"||/\bOpera\b/.test(u)&&(/\bOPR\b/.test(a)?"Blink":"Presto")||/\b(?:Midori|Nook|Safari)\b/i.test(a)&&!/^(?:Trident|EdgeHTML)$/.test(C)&&"WebKit"||!C&&/\bMSIE\b/i.test(a)&&("Mac OS"==v?"Tasman":"Trident")||"WebKit"==C&&/\bPlayStation\b(?! Vita\b)/i.test(u)&&"NetFront")C=[c];"IE"==u&&(c=(/; *(?:XBLWP|ZuneWP)(\d+)/i.exec(a)||0)[1])?(u+=" Mobile",v="Windows Phone "+(/\+$/.test(c)?c:c+".x"),q.unshift("desktop mode")):/\bWPDesktop\b/i.test(a)?(u="IE Mobile",v="Windows Phone 8.x",
q.unshift("desktop mode"),m||(m=(/\brv:([\d.]+)/.exec(a)||0)[1])):"IE"!=u&&"Trident"==C&&(c=/\brv:([\d.]+)/.exec(a))&&(u&&q.push("identifying as "+u+(m?" "+m:"")),u="IE",m=c[1]);if(P){if(h(b,"global"))if(w&&(c=w.lang.System,U=c.getProperty("os.arch"),v=v||c.getProperty("os.name")+" "+c.getProperty("os.version")),z){try{m=b.require("ringo/engine").version.join("."),u="RingoJS"}catch(X){(c=b.system)&&c.global.system==b.system&&(u="Narwhal",v||(v=c[0].os||null))}u||(u="Rhino")}else"object"==typeof b.process&&
!b.process.browser&&(c=b.process)&&("object"==typeof c.versions&&("string"==typeof c.versions.electron?(q.push("Node "+c.versions.node),u="Electron",m=c.versions.electron):"string"==typeof c.versions.nw&&(q.push("Chromium "+m,"Node "+c.versions.node),u="NW.js",m=c.versions.nw)),u||(u="Node.js",U=c.arch,v=c.platform,m=(m=/[\d.]+/.exec(c.version))?m[0]:null));else n(c=b.runtime)==E?(u="Adobe AIR",v=c.flash.system.Capabilities.os):n(c=b.phantom)==T?(u="PhantomJS",m=(c=c.version||null)&&c.major+"."+c.minor+
"."+c.patch):"number"==typeof Q.documentMode&&(c=/\bTrident\/(\d+)/i.exec(a))?(m=[m,Q.documentMode],(c=+c[1]+4)!=m[1]&&(q.push("IE "+m[1]+" mode"),C&&(C[1]=""),m[1]=c),m="IE"==u?String(m[1].toFixed(1)):m[0]):"number"==typeof Q.documentMode&&/^(?:Chrome|Firefox)\b/.test(u)&&(q.push("masking as "+u+" "+m),u="IE",m="11.0",C=["Trident"],v="Windows");v=v&&g(v)}m&&(c=/(?:[ab]|dp|pre|[ab]\d+pre)(?:\d+\+?)?$/i.exec(m)||/(?:alpha|beta)(?: ?\d)?/i.exec(a+";"+(P&&x.appMinorVersion))||/\bMinefield\b/i.test(a)&&
"a")&&(V=/b/i.test(c)?"beta":"alpha",m=m.replace(RegExp(c+"\\+?$"),"")+("beta"==V?N:y)+(/\d+\+?/.exec(c)||""));if("Fennec"==u||"Firefox"==u&&/\b(?:Android|Firefox OS)\b/.test(v))u="Firefox Mobile";else if("Maxthon"==u&&m)m=m.replace(/\.[\d.]+/,".x");else if(/\bXbox\b/i.test(D))"Xbox 360"==D&&(v=null),"Xbox 360"==D&&/\bIEMobile\b/.test(a)&&q.unshift("mobile mode");else if(!/^(?:Chrome|IE|Opera)$/.test(u)&&(!u||D||/Browser|Mobi/.test(u))||"Windows CE"!=v&&!/Mobi/i.test(a))if("IE"==u&&P)try{null===b.external&&
q.unshift("platform preview")}catch(X){q.unshift("embedded")}else(/\bBlackBerry\b/.test(D)||/\bBB10\b/.test(a))&&(c=(RegExp(D.replace(/ +/g," *")+"/([.\\d]+)","i").exec(a)||0)[1]||m)?(c=[c,/BB10/.test(a)],v=(c[1]?(D=null,L="BlackBerry"):"Device Software")+" "+c[0],m=null):this!=e&&"Wii"!=D&&(P&&O||/Opera/.test(u)&&/\b(?:MSIE|Firefox)\b/i.test(a)||"Firefox"==u&&/\bOS X (?:\d+\.){2,}/.test(v)||"IE"==u&&(v&&!/^Win/.test(v)&&5.5<m||/\bWindows XP\b/.test(v)&&8<m||8==m&&!/\bTrident\b/.test(a)))&&!t.test(c=
l.call(e,a.replace(t,"")+";"))&&c.name&&(c="ing as "+c.name+((c=c.version)?" "+c:""),t.test(u)?(/\bIE\b/.test(c)&&"Mac OS"==v&&(v=null),c="identify"+c):(c="mask"+c,u=J?g(J.replace(/([a-z])([A-Z])/g,"$1 $2")):"Opera",/\bIE\b/.test(c)&&(v=null),P||(m=null)),C=["Presto"],q.push(c));else u+=" Mobile";if(c=(/\bAppleWebKit\/([\d.]+\+?)/i.exec(a)||0)[1]){c=[parseFloat(c.replace(/\.(\d)$/,".0$1")),c];if("Safari"==u&&"+"==c[1].slice(-1))u="WebKit Nightly",V="alpha",m=c[1].slice(0,-1);else if(m==c[1]||m==(c[2]=
(/\bSafari\/([\d.]+\+?)/i.exec(a)||0)[1]))m=null;c[1]=(/\bChrome\/([\d.]+)/i.exec(a)||0)[1];537.36==c[0]&&537.36==c[2]&&28<=parseFloat(c[1])&&"WebKit"==C&&(C=["Blink"]);P&&(I||c[1])?(C&&(C[1]="like Chrome"),c=c[1]||(c=c[0],530>c?1:532>c?2:532.05>c?3:533>c?4:534.03>c?5:534.07>c?6:534.1>c?7:534.13>c?8:534.16>c?9:534.24>c?10:534.3>c?11:535.01>c?12:535.02>c?"13+":535.07>c?15:535.11>c?16:535.19>c?17:536.05>c?18:536.1>c?19:537.01>c?20:537.11>c?"21+":537.13>c?23:537.18>c?24:537.24>c?25:537.36>c?26:"Blink"!=
C?"27":"28")):(C&&(C[1]="like Safari"),c=(c=c[0],400>c?1:500>c?2:526>c?3:533>c?4:534>c?"4+":535>c?5:537>c?6:538>c?7:601>c?8:"8"));C&&(C[1]+=" "+(c+="number"==typeof c?".x":/[.+]/.test(c)?"":"+"));"Safari"==u&&(!m||45<parseInt(m))&&(m=c)}"Opera"==u&&(c=/\bzbov|zvav$/.exec(v))?(u+=" ",q.unshift("desktop mode"),"zvav"==c?(u+="Mini",m=null):u+="Mobile",v=v.replace(RegExp(" *"+c+"$"),"")):"Safari"==u&&/\bChrome\b/.exec(C&&C[1])&&(q.unshift("desktop mode"),u="Chrome Mobile",m=null,/\bOS X\b/.test(v)?(L=
"Apple",v="iOS 4.3+"):v=null);m&&0==m.indexOf(c=/[\d.]+$/.exec(v))&&-1<a.indexOf("/"+c+"-")&&(v=String(v.replace(c,"")).replace(/^ +| +$/g,""));C&&!/\b(?:Avant|Nook)\b/.test(u)&&(/Browser|Lunascape|Maxthon/.test(u)||"Safari"!=u&&/^iOS/.test(v)&&/\bSafari\b/.test(C[1])||/^(?:Adobe|Arora|Breach|Midori|Opera|Phantom|Rekonq|Rock|Samsung Internet|Sleipnir|Web)/.test(u)&&C[1])&&(c=C[C.length-1])&&q.push(c);q.length&&(q=["("+q.join("; ")+")"]);L&&D&&0>D.indexOf(L)&&q.push("on "+L);D&&q.push((/^on /.test(q[q.length-
1])?"":"on ")+D);if(v){var W=(c=/ ([\d.+]+)$/.exec(v))&&"/"==v.charAt(v.length-c[0].length-1);v={architecture:32,family:c&&!W?v.replace(c[0],""):v,version:c?c[1]:null,toString:function(){var a=this.version;return this.family+(a&&!W?" "+a:"")+(64==this.architecture?" 64-bit":"")}}}(c=/\b(?:AMD|IA|Win|WOW|x86_|x)64\b/i.exec(U))&&!/\bi686\b/i.test(U)?(v&&(v.architecture=64,v.family=v.family.replace(RegExp(" *"+c),"")),u&&(/\bWOW64\b/i.test(a)||P&&/\w(?:86|32)$/.test(x.cpuClass||x.platform)&&!/\bWin64; x64\b/i.test(a))&&
q.unshift("32-bit")):v&&/^OS X/.test(v.family)&&"Chrome"==u&&39<=parseFloat(m)&&(v.architecture=64);a||(a=null);b={};b.description=a;b.layout=C&&C[0];b.manufacturer=L;b.name=u;b.prerelease=V;b.product=D;b.ua=a;b.version=u&&m;b.os=v||{architecture:null,family:null,version:null,toString:function(){return"null"}};b.parse=l;b.toString=function(){return this.description||""};b.version&&q.unshift(m);b.name&&q.unshift(u);v&&u&&(v!=String(v).split(" ")[0]||v!=u.split(" ")[0]&&!D)&&q.push(D?"("+v+")":"on "+
v);q.length&&(b.description=q.join(" "));return b}var d={"function":!0,object:!0},k=d[typeof window]&&window||this,x=d[typeof exports]&&exports;d=d[typeof module]&&module&&!module.nodeType&&module;var f=x&&d&&"object"==typeof global&&global;!f||f.global!==f&&f.window!==f&&f.self!==f||(k=f);var q=Math.pow(2,53)-1,t=/\bOpera/;f=Object.prototype;var m=f.hasOwnProperty,A=f.toString,z=l();"function"==typeof define&&"object"==typeof define.amd&&define.amd?(k.platform=z,define(function(){return z})):x&&
d?e(z,function(a,d){x[d]=a}):k.platform=z}).call(this);
function buildIOSMeta(){for(var a=[{name:"viewport",content:"width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"},{name:"apple-mobile-web-app-capable",content:"yes"},{name:"apple-mobile-web-app-status-bar-style",content:"black"}],b=0;b<a.length;b++){var g=document.createElement("meta");g.name=a[b].name;g.content=a[b].content;var e=window.document.head.querySelector('meta[name="'+g.name+'"]');e&&e.parentNode.removeChild(e);window.document.head.appendChild(g)}}
function hideIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","none");jQuery(".xxx-ios-fullscreen-scroll").css("display","none");jQuery(".xxx-game-iframe-full").removeClass("xxx-game-iframe-iphone-se")}function buildIOSFullscreenPanel(){jQuery("body").append('<div class="xxx-ios-fullscreen-message"><div class="xxx-ios-fullscreen-swipe"></div></div><div class="xxx-ios-fullscreen-scroll"></div>')}
function showIOSFullscreenPanel(){jQuery(".xxx-ios-fullscreen-message").css("display","block");jQuery(".xxx-ios-fullscreen-scroll").css("display","block")}
function __iosResize(){window.scrollTo(0,0);if("iPhone"===platform.product)switch(window.devicePixelRatio){case 2:switch(window.innerWidth){case 568:320!==window.innerHeight&&jQuery(".xxx-game-iframe-full").addClass("xxx-game-iframe-iphone-se");break;case 667:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;case 3:switch(window.innerWidth){case 736:414===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;
case 724:375===window.innerHeight?hideIOSFullscreenPanel():showIOSFullscreenPanel();break;default:hideIOSFullscreenPanel()}break;default:hideIOSFullscreenPanel()}}function iosResize(){__iosResize();setTimeout(function(){__iosResize()},500)}function iosInIframe(){try{return window.self!==window.top}catch(a){return!0}}$(document).ready(function(){platform&&"iPhone"===platform.product&&!iosInIframe()&&(buildIOSFullscreenPanel(),buildIOSMeta())});
jQuery(window).resize(function(){platform&&"iPhone"===platform.product&&!iosInIframe()&&iosResize()});
(function(){var a="undefined"!==typeof window&&"undefined"!==typeof window.document?window.document:{},b="undefined"!==typeof module&&module.exports,g="undefined"!==typeof Element&&"ALLOW_KEYBOARD_INPUT"in Element,e=function(){for(var b,e=["requestFullscreen exitFullscreen fullscreenElement fullscreenEnabled fullscreenchange fullscreenerror".split(" "),"webkitRequestFullscreen webkitExitFullscreen webkitFullscreenElement webkitFullscreenEnabled webkitfullscreenchange webkitfullscreenerror".split(" "),"webkitRequestFullScreen webkitCancelFullScreen webkitCurrentFullScreenElement webkitCancelFullScreen webkitfullscreenchange webkitfullscreenerror".split(" "),
"mozRequestFullScreen mozCancelFullScreen mozFullScreenElement mozFullScreenEnabled mozfullscreenchange mozfullscreenerror".split(" "),"msRequestFullscreen msExitFullscreen msFullscreenElement msFullscreenEnabled MSFullscreenChange MSFullscreenError".split(" ")],l=0,d=e.length,k={};l<d;l++)if((b=e[l])&&b[1]in a){for(l=0;l<b.length;l++)k[e[0][l]]=b[l];return k}return!1}(),n={change:e.fullscreenchange,error:e.fullscreenerror},h={request:function(b){var r=e.requestFullscreen;b=b||a.documentElement;if(/5\.1[.\d]* Safari/.test(navigator.userAgent))b[r]();
else b[r](g&&Element.ALLOW_KEYBOARD_INPUT)},exit:function(){a[e.exitFullscreen]()},toggle:function(a){this.isFullscreen?this.exit():this.request(a)},onchange:function(a){this.on("change",a)},onerror:function(a){this.on("error",a)},on:function(b,e){var l=n[b];l&&a.addEventListener(l,e,!1)},off:function(b,e){var l=n[b];l&&a.removeEventListener(l,e,!1)},raw:e};e?(Object.defineProperties(h,{isFullscreen:{get:function(){return!!a[e.fullscreenElement]}},element:{enumerable:!0,get:function(){return a[e.fullscreenElement]}},
enabled:{enumerable:!0,get:function(){return!!a[e.fullscreenEnabled]}}}),b?module.exports=h:window.screenfull=h):b?module.exports=!1:window.screenfull=!1})();var s_iScaleFactor=1,s_bIsIphone=!1;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}function isIOS(){var a="iPad Simulator;iPhone Simulator;iPod Simulator;iPad;iPhone;iPod".split(";");for(-1!==navigator.userAgent.toLowerCase().indexOf("iphone")&&(s_bIsIphone=!0);a.length;)if(navigator.platform===a.pop())return!0;return s_bIsIphone=!1}
function getSize(a){var b=a.toLowerCase(),g=window.document,e=g.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var n=g.createElement("body");n.id="vpw-test-b";n.style.cssText="overflow:scroll";var h=g.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+b+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+b+":7px!important}}</style>";n.appendChild(h);e.insertBefore(n,g.head);
a=7==h["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(n)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var b=getSize("Width");_checkOrientation(b,a);var g=Math.min(a/CANVAS_HEIGHT,b/CANVAS_WIDTH),e=CANVAS_WIDTH*g;g*=CANVAS_HEIGHT;if(g<a){var n=a-g;g+=n;e+=CANVAS_WIDTH/CANVAS_HEIGHT*n}else e<b&&(n=b-e,e+=n,g+=CANVAS_HEIGHT/CANVAS_WIDTH*n);n=a/2-g/2;var h=b/2-e/2,r=CANVAS_WIDTH/e;if(h*r<-EDGEBOARD_X||n*r<-EDGEBOARD_Y)g=Math.min(a/(CANVAS_HEIGHT-2*
EDGEBOARD_Y),b/(CANVAS_WIDTH-2*EDGEBOARD_X)),e=CANVAS_WIDTH*g,g*=CANVAS_HEIGHT,n=(a-g)/2,h=(b-e)/2,r=CANVAS_WIDTH/e;s_iOffsetX=-1*h*r;s_iOffsetY=-1*n*r;0<=n&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_bIsIphone?(canvas=document.getElementById("canvas"),s_oStage.canvas.width=2*e,s_oStage.canvas.height=2*g,canvas.style.width=e+"px",canvas.style.height=g+"px",a=Math.min(e/
CANVAS_WIDTH,g/CANVAS_HEIGHT),s_iScaleFactor=2*a,s_oStage.scaleX=s_oStage.scaleY=2*a):s_bMobile&&!1===isIOS()?($("#canvas").css("width",e+"px"),$("#canvas").css("height",g+"px")):(s_oStage.canvas.width=e,s_oStage.canvas.height=g,s_iScaleFactor=Math.min(e/CANVAS_WIDTH,g/CANVAS_HEIGHT),s_oStage.scaleX=s_oStage.scaleY=s_iScaleFactor);0>n?$("#canvas").css("top",n+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px");fullscreenHandler()}}
function _checkOrientation(a,b){s_bMobile&&ENABLE_CHECK_ORIENTATION&&(a>b?"landscape"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),s_oMain.stopUpdate()):"portrait"===$(".orientation-msg-container").attr("data-orientation")?($(".orientation-msg-container").css("display","none"),s_oMain.startUpdate()):($(".orientation-msg-container").css("display","block"),
s_oMain.stopUpdate()))}function createBitmap(a,b,g){var e=new createjs.Bitmap(a),n=new createjs.Shape;b&&g?n.graphics.beginFill("#fff").drawRect(0,0,b,g):n.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=n;return e}function createSprite(a,b,g,e,n,h){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-g,-e,n,h);a.hitArea=b;return a}
function randomFloatBetween(a,b,g){"undefined"===typeof g&&(g=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(g))}function shuffle(a){for(var b=a.length,g,e;0!==b;)e=Math.floor(Math.random()*b),--b,g=a[b],a[b]=a[e],a[e]=g;return a}function formatTime(a){a/=1E3;var b=Math.floor(a/60);a=parseFloat(a-60*b).toFixed(1);var g="";g=10>b?g+("0"+b+":"):g+(b+":");return 10>a?g+("0"+a):g+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};function ctlArcadeResume(){null!==s_oMain&&s_oMain.startUpdate()}function ctlArcadePause(){null!==s_oMain&&s_oMain.stopUpdate()}
function getParamValue(a){for(var b=window.location.search.substring(1).split("&"),g=0;g<b.length;g++){var e=b[g].split("=");if(e[0]==a)return e[1]}}function playSound(a,b,g){return!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(s_aSounds[a].play(),s_aSounds[a].volume(b),s_aSounds[a].loop(g),s_aSounds[a]):null}function stopSound(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].stop()}function setVolume(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].volume(b)}
function setMute(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_aSounds[a].mute(b)}
(function(){function a(a){var e={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in e?document.body.className=e[a.type]:(document.body.className=this[b]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var b="hidden";b in document?document.addEventListener("visibilitychange",a):(b="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(b="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(b="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function fullscreenHandler(){ENABLE_FULLSCREEN&&screenfull.enabled&&(s_bFullscreen=screen.height<window.innerHeight+3&&screen.height>window.innerHeight-3?!0:!1,null!==s_oInterface&&s_oInterface.resetFullscreenBut(),null!==s_oMenu&&s_oMenu.resetFullscreenBut())}if(screenfull.enabled)screenfull.on("change",function(){s_bFullscreen=screenfull.isFullscreen;null!==s_oInterface&&s_oInterface.resetFullscreenBut();null!==s_oMenu&&s_oMenu.resetFullscreenBut()});
function CSpriteLibrary(){var a,b,g,e,n,h;this.init=function(r,p,l){g=b=0;e=r;n=p;h=l;a={}};this.addSprite=function(e,g){a.hasOwnProperty(e)||(a[e]={szPath:g,oSprite:new Image},b++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){n.call(h)};this._onSpriteLoaded=function(){e.call(h);++g===b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return b}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=640,EDGEBOARD_X=300,EDGEBOARD_Y=0,FONT_GAME="walibi0615bold",FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,REEL_OFFSET_X=380,REEL_OFFSET_Y=123,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=10,
WILD_SYMBOL=10,BONUS_SYMBOL=9,NUM_PAYLINES=5,SYMBOL_SIZE=140,SPACE_BETWEEN_SYMBOLS=10,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*SYMBOL_SIZE,REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*SYMBOL_SIZE,TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,MIN_BET,MAX_BET,TOTAL_MONEY,MAX_NUM_HOLD,CHICKEN_WIDTH=166,CHICKEN_HEIGHT=187,NUM_PRIZES=3,NUM_SYMBOLS_FOR_BONUS=3,PERC_WIN_EGG_1,PERC_WIN_EGG_2,PERC_WIN_EGG_3,SOUNDTRACK_VOLUME=.5,WIN_OCCURRENCE,SLOT_CASH,MIN_WIN,BONUS_OCCURRENCE,PAYTABLE_VALUES,BONUS_PRIZE=
[[5,50,100],[10,100,200],[50,200,500]],ENABLE_FULLSCREEN,ENABLE_CHECK_ORIENTATION,SHOW_CREDITS;
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initPaylines();this._initSymbolWin();this._initSymbolAnims();this._initSymbolsOccurence();this._initBonus()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var b={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(b)}};this._initPaylines=
function(){s_aPaylineCombo=[[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}]]};this._initSymbolAnims=function(){s_aSymbolAnims=[];var a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_1_anim")],
frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[0]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_2_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[1]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_3_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,
1],anim:[1,14]}};s_aSymbolAnims[2]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_4_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[3]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_5_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[4]=new createjs.SpriteSheet(a);a={framerate:20,
images:[s_oSpriteLibrary.getSprite("symbol_6_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[5]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_7_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[6]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_8_anim")],frames:{width:SYMBOL_SIZE,
height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[7]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_9_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[8]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_10_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
14]}};s_aSymbolAnims[9]=new createjs.SpriteSheet(a)};this._initSymbolWin=function(){s_aSymbolWin=[];s_aSymbolWin[0]=PAYTABLE_VALUES[0];s_aSymbolWin[1]=PAYTABLE_VALUES[1];s_aSymbolWin[2]=PAYTABLE_VALUES[2];s_aSymbolWin[3]=PAYTABLE_VALUES[3];s_aSymbolWin[4]=PAYTABLE_VALUES[4];s_aSymbolWin[5]=PAYTABLE_VALUES[5];s_aSymbolWin[6]=PAYTABLE_VALUES[6];s_aSymbolWin[7]=PAYTABLE_VALUES[7]};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);
for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=0;4>a;a++)s_aRandSymbols.push(5);for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;7>a;a++)s_aRandSymbols.push(7);for(a=0;8>a;a++)s_aRandSymbols.push(8);for(a=0;2>a;a++)s_aRandSymbols.push(9);for(a=0;1>a;a++)s_aRandSymbols.push(10)};this._initBonus=function(){s_aEggOccurence=[];var a;for(a=0;a<PERC_WIN_EGG_1;a++)s_aEggOccurence.push(0);for(a=0;a<PERC_WIN_EGG_2;a++)s_aEggOccurence.push(1);for(a=0;a<PERC_WIN_EGG_3;a++)s_aEggOccurence.push(2)};
this._init()}var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols,s_aEggOccurence;TEXT_MONEY="MONEY";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_COIN="COIN";TEXT_MAX_BET="MAX BET";TEXT_INFO="INFO";TEXT_LINES="LINES";TEXT_SPIN="SPIN";TEXT_WIN="WIN";TEXT_HOLD="HOLD";TEXT_HELP_WILD="JOLLY SYMBOL CAN REPLACE ANY OTHER SYMBOL TO MAKE UP A COMBO";TEXT_HELP_BONUS="3 OR MORE MR CHICKEN LET YOU PLAY THE BONUS GAME!";TEXT_CREDITS_DEVELOPED="DEVELOPED BY";TEXT_CURRENCY="$";
var TEXT_PRELOADER_CONTINUE="START";TEXT_CONGRATULATIONS="Congratulations!";TEXT_MSG_SHARE1="You collected <strong>";TEXT_MSG_SHARE2=" points</strong>!<br><br>Share your score with your friends!";TEXT_MSG_SHARING1="My score is ";TEXT_MSG_SHARING2=" points! Can you do better?";
function CPreloader(){var a,b,g,e,n,h,r,p,l,d;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.addSprite("200x200","./sprites/200x200.jpg");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.loadSprites();d=new createjs.Container;s_oStage.addChild(d)};this.unload=function(){d.removeAllChildren();l.unload()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=new createjs.Shape;k.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.addChild(k);k=s_oSpriteLibrary.getSprite("200x200");r=createBitmap(k);r.regX=.5*k.width;r.regY=.5*k.height;r.x=CANVAS_WIDTH/2;r.y=CANVAS_HEIGHT/2-180;d.addChild(r);p=new createjs.Shape;p.graphics.beginFill("rgba(0,0,0,0.01)").drawRoundRect(r.x-100,r.y-100,200,200,10);d.addChild(p);r.mask=p;
k=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(k);e.x=CANVAS_WIDTH/2-k.width/2;e.y=CANVAS_HEIGHT/2+50;d.addChild(e);a=k.width;b=k.height;n=new createjs.Shape;n.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(e.x,e.y,1,b);d.addChild(n);e.mask=n;g=new createjs.Text("","30px "+FONT_GAME,"#fff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2+100;g.textBaseline="alphabetic";g.textAlign="center";d.addChild(g);k=s_oSpriteLibrary.getSprite("but_start");l=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/
2,k,TEXT_PRELOADER_CONTINUE,"Arial","#000","bold 40",d);l.addEventListener(ON_MOUSE_UP,this._onButStartRelease,this);l.setVisible(!1);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.addChild(h);createjs.Tween.get(h).to({alpha:0},500).call(function(){createjs.Tween.removeTweens(h);d.removeChild(h)})};this._onButStartRelease=function(){s_oMain._onRemovePreloader()};this.refreshLoader=function(d){g.text=d+"%";100===d&&(l.setVisible(!0),g.visible=!1,e.visible=
!1);n.graphics.clear();d=Math.floor(d*a/100);n.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(e.x,e.y,d,b)};this._init()}
function CMain(a){var b,g=0,e=0,n=STATE_LOADING,h,r;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};
this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();b=!0};this.soundLoaded=function(){g++;h.refreshLoader(Math.floor(g/e*100))};this._initSounds=function(){var a=[];a.push({path:"./sounds/",filename:"win",loop:!0,volume:1,ingamename:"win"});a.push({path:"./sounds/",filename:"press_but",loop:!1,volume:1,ingamename:"press_but"});a.push({path:"./sounds/",filename:"reel_stop",loop:!1,volume:1,ingamename:"reel_stop"});a.push({path:"./sounds/",
filename:"reels",loop:!1,volume:1,ingamename:"reels"});a.push({path:"./sounds/",filename:"choose_chicken",loop:!1,volume:1,ingamename:"choose_chicken"});a.push({path:"./sounds/",filename:"start_reel",loop:!1,volume:1,ingamename:"start_reel"});a.push({path:"./sounds/",filename:"press_hold",loop:!1,volume:1,ingamename:"press_hold"});a.push({path:"./sounds/",filename:"reveal_egg",loop:!1,volume:1,ingamename:"reveal_egg"});a.push({path:"./sounds/",filename:"soundtrack",loop:!0,volume:1,ingamename:"soundtrack"});
a.push({path:"./sounds/",filename:"soundtrack_bonus",loop:!0,volume:1,ingamename:"soundtrack_bonus"});e+=a.length;s_aSounds=[];for(var b=0;b<a.length;b++)s_aSounds[a[b].ingamename]=new Howl({src:[a[b].path+a[b].filename+".mp3"],autoplay:!1,preload:!0,loop:a[b].loop,volume:a[b].volume,onload:s_oMain.soundLoaded})};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu",
"./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.jpg");s_oSpriteLibrary.addSprite("but_play_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("spin_but","./sprites/but_spin_bg.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");s_oSpriteLibrary.addSprite("info_but","./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("bet_but",
"./sprites/bet_but.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg","./sprites/but_maxbet_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hit_area_col","./sprites/hit_area_col.png");s_oSpriteLibrary.addSprite("hold_col","./sprites/hold_col.png");s_oSpriteLibrary.addSprite("bonus_bg","./sprites/bonus_bg.jpg");
s_oSpriteLibrary.addSprite("chicken","./sprites/chicken.png");s_oSpriteLibrary.addSprite("hit_area_chicken","./sprites/hit_area_chicken.png");s_oSpriteLibrary.addSprite("egg","./sprites/egg.png");s_oSpriteLibrary.addSprite("but_credits","./sprites/but_credits.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");for(var a=1;a<NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+
a,"./sprites/symbol_"+a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.png");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+a,"./sprites/payline_"+a+".png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){g++;h.refreshLoader(Math.floor(g/e*100))};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this._onRemovePreloader=function(){h.unload();
s_oSoundTrack=playSound("soundtrack",1,!0);this.gotoMenu()};this.gotoMenu=function(){new CMenu;n=STATE_MENU};this.gotoGame=function(){r=new CGame(p);n=STATE_GAME};this.gotoHelp=function(){new CHelp;n=STATE_HELP};this.stopUpdate=function(){b=!1;createjs.Ticker.paused=!0;$("#block_game").css("display","block");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Howler.mute(!0)};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();b=!0;createjs.Ticker.paused=!1;$("#block_game").css("display","none");
(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&s_bAudioActive&&Howler.mute(!1)};this._update=function(a){if(!1!==b){var d=(new Date).getTime();s_iTimeElaps=d-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=d;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);n===STATE_GAME&&r.update();s_oStage.update(a)}};s_oMain=this;var p=a;PAYTABLE_VALUES=[];for(var l=0;8>l;l++)PAYTABLE_VALUES[l]=a["paytable_symbol_"+(l+1)];ENABLE_FULLSCREEN=p.fullscreen;ENABLE_CHECK_ORIENTATION=p.check_orientation;
SHOW_CREDITS=p.show_credits;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_bFullscreen=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null;
function CTextButton(a,b,g,e,n,h,r,p){var l,d,k,x,f,q,t,m,A,z;this._init=function(a,b,e,q,g,h,r){l=!1;x=[];f=[];z=createBitmap(e);d=e.width;k=e.height;A=new createjs.Text(q,r+"px "+g,h);A.textAlign="center";A.shadow=new createjs.Shadow("#000",2,2,2);A.textBaseline="middle";A.lineHeight=24;A.x=e.width/2;A.y=e.height/2;m=new createjs.Container;m.x=a;m.y=b;m.regX=e.width/2;m.regY=e.height/2;m.cursor="pointer";m.addChild(z,A);p.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",
q);m.off("pressup",t);p.removeChild(m)};this.setVisible=function(a){m.visible=a};this.enable=function(){l=!1;z.filters=[];z.cache(0,0,d,k)};this.disable=function(){l=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100);z.filters=[new createjs.ColorMatrixFilter(a)];z.cache(0,0,d,k)};this._initListener=function(){q=m.on("mousedown",this.buttonDown);t=m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){x[a]=b;f[a]=d};this.buttonRelease=function(){l||(playSound("press_but",
1,!1),m.scaleX=1,m.scaleY=1,x[ON_MOUSE_UP]&&x[ON_MOUSE_UP].call(f[ON_MOUSE_UP]))};this.buttonDown=function(){l||(m.scaleX=.9,m.scaleY=.9,x[ON_MOUSE_DOWN]&&x[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){m.x=a;m.y=b};this.changeText=function(a){A.text=a};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,b,g,e,n,h,r);return this}
function CGfxButton(a,b,g,e){var n,h,r,p,l,d,k,x,f;this._init=function(a,b,d,k){n=!1;p=[];l=[];f=createBitmap(d);f.x=a;f.y=b;h=d.width;r=d.height;f.regX=d.width/2;f.regY=d.height/2;f.cursor="pointer";!1!==k&&s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",d);f.off("pressup",k);s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this.enable=function(){n=!1;f.filters=[];f.cache(0,0,h,r)};this.disable=function(){n=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);
f.filters=[new createjs.ColorMatrixFilter(a)];f.cache(0,0,h,r)};this._initListener=function(){d=f.on("mousedown",this.buttonDown);k=f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){p[a]=b;l[a]=d};this.addEventListenerWithParams=function(a,b,d,k){p[a]=b;l[a]=d;x=k};this.buttonRelease=function(){n||(playSound("press_but",1,!1),f.scaleX=1,f.scaleY=1,p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(l[ON_MOUSE_UP],x))};this.buttonDown=function(){n||(f.scaleX=.9,f.scaleY=.9,p[ON_MOUSE_DOWN]&&
p[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN],x))};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this.getSprite=function(){return f};this._init(a,b,g,e);return this}
function CToggle(a,b,g,e,n){var h,r,p,l,d,k,x;this._init=function(a,b,d,k,e){x=void 0!==e?e:s_oStage;r=[];p=[];e=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});h=k;l=createSprite(e,"state_"+h,d.width/2/2,d.height/2,d.width/2,d.height);l.x=a;l.y=b;l.stop();s_bMobile||(l.cursor="pointer");x.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",d);l.off("pressup",k);x.removeChild(l)};
this._initListener=function(){d=l.on("mousedown",this.buttonDown);k=l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,d,b){r[a]=d;p[a]=b};this.setCursorType=function(a){l.cursor=a};this.setActive=function(a){h=a;l.gotoAndStop("state_"+h)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;playSound("press_but",1,!1);h=!h;l.gotoAndStop("state_"+h);r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(p[ON_MOUSE_UP],h)};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN])};
this.setPosition=function(a,d){l.x=a;l.y=d};this._init(a,b,g,e,n)}
function CBetBut(a,b,g){var e,n,h,r=[],p;this._init=function(a,d,b){e=!1;n=[];h=[];b=s_oSpriteLibrary.getSprite("bet_but");var k=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:0,regY:0},animations:{on:[0,1],off:[1,2]}});p=createSprite(k,"on",0,0,b.width/2,b.height);p.stop();p.x=a;p.y=d;p.regX=b.width/2;p.regY=b.height/2;s_oStage.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown",this.buttonDown);p.off("pressup",this.buttonRelease);s_oStage.removeChild(p)};
this.disable=function(a){e=a};this.setVisible=function(a){p.visible=a};this.setOn=function(){p.gotoAndStop("on")};this.setOff=function(){p.gotoAndStop("off")};this._initListener=function(){p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,k){n[a]=b;h[a]=k};this.addEventListenerWithParams=function(a,b,k,e){n[a]=b;h[a]=k;r=e};this.buttonRelease=function(){n[ON_MOUSE_UP]&&!1===e&&(playSound("press_but",1,!1),n[ON_MOUSE_UP].call(h[ON_MOUSE_UP],r))};
this.buttonDown=function(){n[ON_MOUSE_DOWN]&&!1===e&&n[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],r)};this.setPosition=function(a,b){p.x=a;p.y=b};this.setX=function(a){p.x=a};this.setY=function(a){p.y=a};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};this._init(a,b,g)}
function CMenu(){var a,b,g,e,n,h,r=null,p=null,l,d,k,x,f,q;this._init=function(){l=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(l);var t=s_oSpriteLibrary.getSprite("but_play_bg");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-60,t,TEXT_PLAY,FONT_GAME,"#ffffff",32,s_oStage);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),n=CANVAS_WIDTH-t.width/4-10,h=t.height/2+10,k=new CToggle(n,
h,t,s_bAudioActive,s_oStage),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),null===s_oSoundTrack?s_oSoundTrack=playSound("soundtrack",SOUNDTRACK_VOLUME,!0):setVolume("soundtrack",1);SHOW_CREDITS?(t=s_oSpriteLibrary.getSprite("but_credits"),a=t.height/2+10,b=t.height/2+10,x=new CGfxButton(a,b,t,s_oStage),x.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this),g=a+t.width+10,e=b):(g=t.height/2+10,e=t.height/2+10);t=window.document;var m=t.documentElement;r=m.requestFullscreen||m.mozRequestFullScreen||
m.webkitRequestFullScreen||m.msRequestFullscreen;p=t.exitFullscreen||t.mozCancelFullScreen||t.webkitExitFullscreen||t.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(r=!1);r&&screenfull.enabled&&(t=s_oSpriteLibrary.getSprite("but_fullscreen"),f=new CToggle(g,e,t,s_bFullscreen,s_oStage),f.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));q=new createjs.Shape;q.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(q);createjs.Tween.get(q).to({alpha:0},600).call(function(){q.visible=
!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(d,p){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(n-d,p+h);SHOW_CREDITS&&x.setPosition(a+d,b+p);r&&screenfull.enabled&&f.setPosition(g+d,e+p)};this.unload=function(){d.unload();d=null;SHOW_CREDITS&&x.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;r&&screenfull.enabled&&f.unload();s_oStage.removeAllChildren();s_oMenu=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame();
$(s_oMain).trigger("start_session")};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButCreditsRelease=function(){new CCreditsPanel};this.resetFullscreenBut=function(){r&&screenfull.enabled&&f.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?p.call(window.document):r.call(window.document.documentElement);sizeHandler()};s_oMenu=this;this._init()}var s_oMenu=null;
function CGame(a){var b=!1,g,e=!0,n,h,r,p,l,d,k,x,f,q,t,m,A=0,z,E,B,M,G,K,F,H,I,S,R,w,T,y,N=null,Q;this._init=function(){h=GAME_STATE_IDLE;n=!0;E=m=l=r=0;K=[0,1,2,3,4];p=K[0];d=NUM_PAYLINES;t=TOTAL_MONEY;f=MIN_BET;q=f*d;F=[];for(var a=0;a<NUM_ROWS;a++){F[a]=[];for(var c=0;c<NUM_REELS;c++)F[a][c]=0}s_oTweenController=new CTweenController;w=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(w);this._initReels();T=createBitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oStage.addChild(T);
this._initStaticSymbols();this._initHitAreaColumn();y=new CInterface(f,q,t);Q=new CBonusPanel;N=new CPayTablePanel;t<q&&y.disableSpin();b=!0};this.unload=function(){stopSound("reels");s_oStage.removeChild(w);s_oStage.removeChild(T);y.unload();N.unload();for(var a=0;a<B.length;a++)B[a].unload();for(a=0;a<NUM_ROWS;a++)for(var c=0;c<NUM_REELS;c++)M[a][c].unload();Q.unload()};this._initReels=function(){var a=REEL_OFFSET_X,c=REEL_OFFSET_Y,b=0;B=[];for(var d=0;d<NUM_REELS;d++)B[d]=new CReelColumn(d,a,c,
b),B[d+NUM_REELS]=new CReelColumn(d+NUM_REELS,a,c+SYMBOL_SIZE*NUM_ROWS,b),a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS,b+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,c=REEL_OFFSET_Y;M=[];for(var b=0;b<NUM_ROWS;b++){M[b]=[];for(var d=0;d<NUM_REELS;d++){var e=new CStaticSymbolCell(b,d,a,c);M[b][d]=e;a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;c+=SYMBOL_SIZE}};this._initHitAreaColumn=function(){R=[];S=[];b=376;d=120;for(var a=0;a<NUM_REELS;a++){var c=createBitmap(s_oSpriteLibrary.getSprite("hold_col"));
c.x=b;c.y=d;c.visible=!1;s_oStage.addChild(c);b+=150;S.push(c);R[a]=!1}H=[];I=[];var b=381,d=108;a=s_oSpriteLibrary.getSprite("hit_area_col");for(c=0;c<NUM_REELS;c++){var e=new createjs.Text(TEXT_HOLD,"22px "+FONT_GAME,"#ffffff");e.visible=!1;e.x=b+a.width/2;e.y=d+a.height-20;e.shadow=new createjs.Shadow("#000",1,1,2);e.textAlign="center";s_oStage.addChild(e);H[c]=e;e=new CGfxButton(b+a.width/2,d+a.height/2,a);e.setVisible(!1);e.addEventListenerWithParams(ON_MOUSE_UP,this._onHitAreaCol,this,{index:c});
b+=150;I.push(e)}};this.generateFinalSymbols=function(){for(var a=0;a<NUM_ROWS;a++)for(var c=0;c<NUM_REELS;c++)!1===B[c].isHold()&&(F[a][c]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]);a=this._checkForCombos();this._checkForBonus();return a};this._checkForCombos=function(){G=[];for(var a=z=0;a<d;a++){var c=s_aPaylineCombo[a],b=[],e=F[c[0].row][c[0].col];if(e!==BONUS_SYMBOL){var k=1,f=1;for(b.push({row:c[0].row,col:c[0].col,value:F[c[0].row][c[0].col]});e===WILD_SYMBOL&&f<NUM_REELS;)k++,
e=F[c[f].row][c[f].col],b.push({row:c[f].row,col:c[f].col,value:F[c[f].row][c[f].col]}),f++;for(;f<c.length;f++)if(F[c[f].row][c[f].col]===e||F[c[f].row][c[f].col]===WILD_SYMBOL){if(F[c[f].row][c[f].col]===BONUS_SYMBOL)break;k++;b.push({row:c[f].row,col:c[f].col,value:F[c[f].row][c[f].col]})}else break;e!==BONUS_SYMBOL&&0<s_aSymbolWin[e-1][k-1]&&(z+=s_aSymbolWin[e-1][k-1],G.push({line:a+1,amount:s_aSymbolWin[e-1][k-1],num_win:k,value:e,list:b}))}}return z>q?!0:!1};this._checkForBonus=function(){g=
!1;A=0;for(var a=[],c=0;c<NUM_ROWS;c++)for(var b=0;b<NUM_REELS;b++)F[c][b]===BONUS_SYMBOL&&(a.push({row:c,col:b,value:F[c][b]}),A++);A>=NUM_SYMBOLS_FOR_BONUS&&(G.push({line:-1,amount:0,num_win:A,value:BONUS_SYMBOL,list:a}),5<A&&(A=5),g=!0)};this._generateRandSymbols=function(){for(var a=[],c=0;c<NUM_ROWS;c++)a[c]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)];return a};this.reelArrived=function(a,c){if(r>MIN_REEL_LOOPS)if(p===c){if(!1===B[a].isReadyToStop()){var b=a;a<NUM_REELS?(b+=
NUM_REELS,B[b].setReadyToStop(),B[a].restart([F[0][a],F[1][a],F[2][a]],!0)):(b-=NUM_REELS,B[b].setReadyToStop(),B[a].restart([F[0][b],F[1][b],F[2][b]],!0))}}else B[a].restart(this._generateRandSymbols(),!1);else B[a].restart(this._generateRandSymbols(),!1),0===a&&r++};this.increaseReelLoops=function(){r+=2};this.stopNextReel=function(){l++;0===l%2&&(playSound("reel_stop",.3,!1),p=K[l/2],l===2*NUM_REELS&&this._endReelAnimation())};this._endReelAnimation=function(){stopSound("reels");l=r=0;p=K[0];for(var a=
0;a<NUM_REELS;a++)R[a]=!1,S[a].visible=!1,B[a].setHold(!1),B[a+NUM_REELS].setHold(!1);m=0;if(0<G.length){for(var c=0;c<G.length;c++){N.highlightCombo(G[c].value,G[c].num_win);-1!==G[c].line&&y.showLine(G[c].line);var b=G[c].list;for(a=0;a<b.length;a++)M[b[a].row][b[a].col].show(b[a].value)}z*=f;t+=z;SLOT_CASH-=z;0<z&&(y.refreshMoney(t),y.refreshWinText(z));k=0;h=GAME_STATE_SHOW_ALL_WIN;playSound("win",1,!1);n=!0;!1===g&&(y.disableBetBut(!1),y.enableGuiButtons())}else n?(this.enableColumnHitArea(),
n=!1,y.enableSpin(),y.disableMaxBet()):(y.disableBetBut(!1),y.enableGuiButtons(),n=!0),h=GAME_STATE_IDLE;t<q&&y.disableSpin();E++;E===O&&(E=0,$(s_oMain).trigger("show_interlevel_ad"));$(s_oMain).trigger("save_score",t)};this.hidePayTable=function(){N.hide()};this._showWin=function(){if(0<x){stopSound("win");if(-1!==G[x-1].line){var a=G[x-1].line;y.hideLine(a)}a=G[x-1].list;for(var c=0;c<a.length;c++)M[a[c].row][a[c].col].stopAnim()}x===G.length&&(x=0);-1!==G[x].line&&(a=G[x].line,y.showLine(a));a=
G[x].list;for(c=0;c<a.length;c++)M[a[c].row][a[c].col].show(a[c].value);x++};this._hideAllWins=function(){for(var a=0;a<G.length;a++)for(var c=G[a].list,b=0;b<c.length;b++)M[c[b].row][c[b].col].stopAnim();y.hideAllLines();x=k=0;k=TIME_SHOW_WIN;h=GAME_STATE_SHOW_WIN;g&&Q.show(A,f)};this.enableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)H[a].visible=!0,I[a].setVisible(!0)};this.disableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)H[a].visible=!1,I[a].setVisible(!1)};this.activateLines=
function(a){d=a;this.removeWinShowing();q=a=f*d;y.refreshTotalBet(q);y.refreshNumLines(d);a>t?y.disableSpin():y.enableSpin()};this.addLine=function(){d===NUM_PAYLINES?d=1:d++;var a=f*d;q=a;q=Math.floor(100*q)/100;y.refreshTotalBet(q);y.refreshNumLines(d);a>t?y.disableSpin():y.enableSpin()};this.changeCoinBet=function(){var a=Math.floor(100*(f+.05))/100;a>MAX_BET?(f=MIN_BET,q=f*d,q=Math.floor(100*q)/100,y.refreshBet(f),y.refreshTotalBet(q),a=q):(a*=d,f+=.05,f=Math.floor(100*f)/100,q=a,q=Math.floor(100*
q)/100,y.refreshBet(f),y.refreshTotalBet(q));a>t?y.disableSpin():y.enableSpin()};this.onMaxBet=function(){var a=MAX_BET;d=NUM_PAYLINES;a*=d;f=MAX_BET;q=a;y.refreshBet(f);y.refreshTotalBet(q);y.refreshNumLines(d);a>t?y.disableSpin():(y.enableSpin(),this.onSpin())};this._onHitAreaCol=function(a){a=a.index;!0===R[a]?(R[a]=!1,S[a].visible=!1,H[a].visible=!0,m--,B[a].setHold(!1),B[a+NUM_REELS].setHold(!1)):m<MAX_NUM_HOLD&&(R[a]=!0,m++,S[a].visible=!0,H[a].visible=!1,B[a].setHold(!0),B[a+NUM_REELS].setHold(!0),
playSound("press_hold",1,!1))};this.removeWinShowing=function(){N.resetHighlightCombo();y.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var c=0;c<NUM_REELS;c++)M[a][c].hide();for(a=0;a<B.length;a++)B[a].activate();h=GAME_STATE_IDLE};this.endBonus=function(a){a*=f;t+=a;y.refreshMoney(t);SLOT_CASH-=a;y.disableBetBut(!1);y.enableGuiButtons();$(s_oMain).trigger("bonus_end",t);$(s_oMain).trigger("save_score",t)};this.onSpin=function(){stopSound("win");playSound("reels",.3,!1);this.disableColumnHitArea();y.disableBetBut(!0);
this.removeWinShowing();MIN_WIN=s_aSymbolWin[0][s_aSymbolWin[0].length-1];for(var a=0;a<s_aSymbolWin.length;a++)for(var c=s_aSymbolWin[a],b=0;b<c.length;b++)0!==c[b]&&c[b]<MIN_WIN&&(MIN_WIN=c[b]);MIN_WIN*=f;n&&(t-=q,y.refreshMoney(t),SLOT_CASH+=q,$(s_oMain).trigger("bet_placed",{bet:f,tot_bet:q}));if(!e&&B[0].visible&&B[1].visible&&this._checkForCombos())this._assignWin();else if(SLOT_CASH<MIN_WIN){do a=this.generateFinalSymbols();while(!0===a||g)}else if(Math.floor(100*Math.random())>WIN_OCCURRENCE){do a=
this.generateFinalSymbols();while(!0===a||g)}else this._assignWin();y.hideAllLines();y.disableGuiButtons();e=!1;h=GAME_STATE_SPINNING};this._printFinalSymbols=function(){for(var a=0;a<NUM_ROWS;a++)for(var c=0;c<NUM_REELS;c++)trace("_aFinalSymbolCombo["+a+"]["+c+"]: "+F[a][c])};this._assignWin=function(){if(SLOT_CASH<BONUS_PRIZE[0][0]*f){var a=0;do{var c=this.generateFinalSymbols();a++}while((!1===c||z*f>SLOT_CASH||g)&&1E4>=a)}else if(Math.floor(100*Math.random())>=BONUS_OCCURRENCE){a=0;do c=this.generateFinalSymbols(),
a++;while((!1===c||z*f>SLOT_CASH||g)&&1E4>=a)}else{a=0;do{c=this.generateFinalSymbols();var b=0;g&&(b=A-3);a++}while((!1===c||z*f+BONUS_PRIZE[b][0]*f>SLOT_CASH||!1===g)&&1E4>=a)}if(1E4<a){do c=this.generateFinalSymbols();while(!0===c||g)}};this.onInfoClicked=function(){h!==GAME_STATE_SPINNING&&(N.isVisible()?N.hide():N.show())};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("end_session");$(s_oMain).trigger("share_event",{img:"200x200.jpg",title:TEXT_CONGRATULATIONS,msg:TEXT_MSG_SHARE1+
t+TEXT_MSG_SHARE2,msg_share:TEXT_MSG_SHARING1+t+TEXT_MSG_SHARING2})};this.getState=function(){return h};this.update=function(){if(!1!==b)switch(h){case GAME_STATE_SPINNING:for(var a=0;a<B.length;a++)B[a].update(p);break;case GAME_STATE_SHOW_ALL_WIN:k+=s_iTimeElaps;k>TIME_SHOW_ALL_WINS&&this._hideAllWins();break;case GAME_STATE_SHOW_WIN:k+=s_iTimeElaps,k>TIME_SHOW_WIN&&(k=0,this._showWin())}};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;SLOT_CASH=a.slot_cash;BONUS_OCCURRENCE=a.bonus_occurrence;MIN_REEL_LOOPS=
a.min_reel_loop;REEL_DELAY=a.reel_delay;TIME_SHOW_WIN=a.time_show_win;TIME_SHOW_ALL_WINS=a.time_show_all_wins;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;MAX_NUM_HOLD=a.max_hold;PERC_WIN_EGG_1=a.perc_win_egg_1;PERC_WIN_EGG_2=a.perc_win_egg_2;PERC_WIN_EGG_3=a.perc_win_egg_3;var O=a.num_spin_ads_showing;new CSlotSettings;this._init()}var s_oGame,s_oTweenController;
function CReelColumn(a,b,g,e){var n,h,r,p,l,d,k,x,f,q,t,m,A,z,E;this._init=function(a,b,e,g){p=r=h=n=!1;x=0;l=a;k=g;d=l<NUM_REELS?l:l-NUM_REELS;q=0;t=MAX_FRAMES_REEL_EASE;f=REEL_STATE_START;m=e;A=m+SYMBOL_SIZE*NUM_ROWS;this.initContainer(b,e)};this.initContainer=function(a,b){E=new createjs.Container;E.x=a;E.y=b;var d=0;z=[];for(var e=0;e<NUM_ROWS;e++){var f=createSprite(s_aSymbolData[s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);f.stop();f.x=
0;f.y=d;E.addChild(f);z[e]=f;d+=SYMBOL_SIZE}s_oStage.addChild(E)};this.unload=function(){s_oStage.removeChild(E)};this.activate=function(){m=E.y;A=m+SYMBOL_SIZE*NUM_ROWS;n=!0};this._setSymbol=function(a){E.removeAllChildren();for(var b=0,d=0;d<a.length;d++){var e=new createSprite(s_aSymbolData[a[d]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);e.stop();e.x=0;e.y=b;E.addChild(e);z[d]=e;b+=SYMBOL_SIZE}};this.setHold=function(a){p=a};this.restart=function(a,b){E.y=m=REEL_START_Y;A=m+SYMBOL_SIZE*NUM_ROWS;this._setSymbol(a);
if(h=b){q=0;t=MAX_FRAMES_REEL_EASE;f=REEL_STATE_STOP;for(var d=0;d<NUM_ROWS;d++)z[d].gotoAndStop("static");r=!0}else for(d=0;d<NUM_ROWS;d++)z[d].gotoAndStop("moving")};this.setReadyToStop=function(){q=0;t=MAX_FRAMES_REEL_EASE;f=REEL_STATE_STOP};this.isReadyToStop=function(){return h};this.isHold=function(){return p};this._updateStart=function(){0===q&&l<NUM_REELS&&playSound("start_reel",.3,!1);q++;q>t&&(q=0,t/=2,f++,m=E.y,A=m+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeInBack(q,0,1,t);a=s_oTweenController.tweenValue(m,
A,a);E.y=a};this._updateMoving=function(){q++;q>t&&(q=0,m=E.y,A=m+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeLinear(q,0,1,t);a=s_oTweenController.tweenValue(m,A,a);E.y=a};this._updateStopping=function(){q++;if(q>=t)n=!1,q=0,t=MAX_FRAMES_REEL_EASE,f=REEL_STATE_START,x=0,h=!1,r&&(r=!1,E.y=REEL_OFFSET_Y),s_oGame.stopNextReel();else{var a=s_oTweenController.easeOutCubic(q,0,1,t);a=s_oTweenController.tweenValue(m,A,a);E.y=a}};this.update=function(a){if(!1!==n&&(x++,x>k))if(p)a===l&&(n=!1,s_oGame.stopNextReel(),
s_oGame.stopNextReel(),0===l&&s_oGame.increaseReelLoops());else switch(!1===h&&E.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(l,d),f){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,b,g,e)}
function CInterface(a,b,g){var e,n,h,r,p,l,d,k,x,f,q,t,m,A,z,E,B=null,M=null,G,K,F,H;this._init=function(a,b,g){var w=s_oSpriteLibrary.getSprite("but_exit");h=CANVAS_WIDTH-w.width/2-10;r=w.height/2+10;x=new CGfxButton(h,r,w,!0);x.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var I=s_oSpriteLibrary.getSprite("audio_icon");p=x.getX()-I.width/2;l=w.height/2+10;m=new CToggle(p,l,I,s_bAudioActive,s_oStage);m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);e=p-I.width/2;n=l}else e=x.getX()-w.width,n=w.height/2+10;w=window.document;I=w.documentElement;B=I.requestFullscreen||I.mozRequestFullScreen||I.webkitRequestFullScreen||I.msRequestFullscreen;M=w.exitFullscreen||w.mozCancelFullScreen||w.webkitExitFullscreen||w.msExitFullscreen;!1===ENABLE_FULLSCREEN&&(B=!1);B&&screenfull.enabled&&(w=s_oSpriteLibrary.getSprite("but_fullscreen"),E=new CToggle(e,n,w,s_bFullscreen,s_oStage),E.addEventListener(ON_MOUSE_UP,this._onFullscreenRelease,this));w=s_oSpriteLibrary.getSprite("spin_but");
f=new CTextButton(1090+w.width/2,CANVAS_HEIGHT-w.height/2,w,"",FONT_GAME,"#ffde00",22,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onSpin,this);w=s_oSpriteLibrary.getSprite("info_but");q=new CTextButton(328+w.width/2,CANVAS_HEIGHT-w.height/2,w,TEXT_INFO,FONT_GAME,"#ffffff",30,s_oStage);q.addEventListener(ON_MOUSE_UP,this._onInfo,this);w=s_oSpriteLibrary.getSprite("but_lines_bg");t=new CTextButton(494+w.width/2,CANVAS_HEIGHT-w.height/2,w,TEXT_LINES,FONT_GAME,"#ffffff",30,s_oStage);t.addEventListener(ON_MOUSE_UP,
this._onAddLine,this);w=s_oSpriteLibrary.getSprite("coin_but");A=new CTextButton(680+w.width/2,CANVAS_HEIGHT-w.height/2,w,TEXT_COIN,FONT_GAME,"#ffffff",30,s_oStage);A.addEventListener(ON_MOUSE_UP,this._onBet,this);w=s_oSpriteLibrary.getSprite("but_maxbet_bg");z=new CTextButton(866+w.width/2,CANVAS_HEIGHT-w.height/2,w,TEXT_MAX_BET,FONT_GAME,"#ffffff",30,s_oStage);z.addEventListener(ON_MOUSE_UP,this._onMaxBet,this);K=new createjs.Text(TEXT_MONEY+"\n"+g.toFixed(2)+TEXT_CURRENCY,"30px "+FONT_GAME,"#ffde00");
K.x=450;K.y=46;K.textBaseline="alphabetic";K.lineHeight=28;K.textAlign="center";s_oStage.addChild(K);H=new createjs.Text(NUM_PAYLINES,"26px "+FONT_GAME,"#ffffff");H.x=584;H.y=CANVAS_HEIGHT-65;H.shadow=new createjs.Shadow("#000",2,2,2);H.textAlign="center";H.textBaseline="alphabetic";s_oStage.addChild(H);G=new createjs.Text(a.toFixed(2),"26px "+FONT_GAME,"#ffffff");G.x=776;G.y=CANVAS_HEIGHT-65;G.shadow=new createjs.Shadow("#000",2,2,2);G.textAlign="center";G.textBaseline="alphabetic";s_oStage.addChild(G);
F=new createjs.Text(TEXT_BET+": "+b.toFixed(2),"26px "+FONT_GAME,"#ffffff");F.x=980;F.y=CANVAS_HEIGHT-65;F.shadow=new createjs.Shadow("#000",2,2,2);F.textAlign="center";F.textBaseline="alphabetic";s_oStage.addChild(F);w=s_oSpriteLibrary.getSprite("bet_but");d=[];a=new CBetBut(334+w.width/2,282+w.height/2);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);d[0]=a;a=new CBetBut(334+w.width/2,180+w.height/2);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,2);
d[1]=a;a=new CBetBut(334+w.width/2,432+w.height/2);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,3);d[2]=a;a=new CBetBut(334+w.width/2,114+w.height/2);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);d[3]=a;a=new CBetBut(334+w.width/2,502+w.height/2);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,5);d[4]=a;k=[];for(a=0;a<NUM_PAYLINES;a++)b=new createjs.Bitmap(s_oSpriteLibrary.getSprite("payline_"+(a+1))),b.visible=!1,s_oStage.addChild(b),
k[a]=b;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){x.unload();x=null;f.unload();f=null;q.unload();q=null;t.unload();t=null;A.unload();A=null;z.unload();z=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;B&&screenfull.enabled&&E.unload();for(var a=0;a<NUM_PAYLINES;a++)d[a].unload();s_oStage.removeAllChildren();s_oInterface=null};this.refreshButtonPos=function(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(p-a,b+l);B&&screenfull.enabled&&E.setPosition(e-
a,n+b);x.setPosition(h-a,b+r)};this.refreshMoney=function(a){K.text=TEXT_MONEY+"\n"+a.toFixed(2)+TEXT_CURRENCY};this.refreshBet=function(a){G.text=a.toFixed(2)};this.refreshTotalBet=function(a){F.text=TEXT_BET+": "+a.toFixed(2)};this.refreshNumLines=function(a){H.text=a;for(var b=0;b<NUM_PAYLINES;b++)b<a?(d[b].setOn(),k[b].visible=!0):d[b].setOff();setTimeout(function(){for(var a=0;a<NUM_PAYLINES;a++)k[a].visible=!1},1E3)};this.resetWin=function(){f.changeText("")};this.refreshWinText=function(a){f.changeText(TEXT_WIN+
"\n"+a.toFixed(2))};this.showLine=function(a){k[a-1].visible=!0};this.hideLine=function(a){k[a-1].visible=!1};this.hideAllLines=function(){for(var a=0;a<NUM_PAYLINES;a++)k[a].visible=!1};this.disableBetBut=function(a){for(var b=0;b<NUM_PAYLINES;b++)d[b].disable(a)};this.enableGuiButtons=function(){f.enable();z.enable();A.enable();t.enable();q.enable()};this.enableSpin=function(){f.enable();z.enable()};this.disableSpin=function(){f.disable();z.disable()};this.enableMaxBet=function(){z.enable()};this.disableMaxBet=
function(){z.disable()};this.disableGuiButtons=function(){f.disable();z.disable();A.disable();t.disable();q.disable()};this._onBetLineClicked=function(a){this.refreshNumLines(a);s_oGame.activateLines(a)};this._onExit=function(){s_oGame.onExit()};this._onSpin=function(){s_oGame.onSpin()};this._onAddLine=function(){s_oGame.addLine()};this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};this._onAudioToggle=function(){Howler.mute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this.resetFullscreenBut=function(){B&&screenfull.enabled&&E.setActive(s_bFullscreen)};this._onFullscreenRelease=function(){s_bFullscreen?M.call(window.document):B.call(window.document.documentElement);sizeHandler()};s_oInterface=this;this._init(a,b,g);return this}var s_oInterface=null;
function CPayTablePanel(){var a,b,g,e,n,h;this._init=function(){h=new createjs.Container;n=createBitmap(s_oSpriteLibrary.getSprite("paytable"));h.addChild(n);this._createPayouts();g=new createjs.Text(TEXT_HELP_WILD,"21px "+FONT_GAME,"#ffff00");g.textAlign="center";g.lineWidth=220;g.lineHeight=22;g.x=635;g.y=284;h.addChild(g);e=new createjs.Text(TEXT_HELP_BONUS,"21px "+FONT_GAME,"#ffff00");e.textAlign="center";e.lineHeight=22;e.lineWidth=220;e.x=1012;e.y=294;h.addChild(e);h.visible=!1;s_oStage.addChild(h);
var a=this;h.on("pressup",function(){a._onExit()})};this.unload=function(){var e=this;h.off("pressup",function(){e._onExit()});s_oStage.removeChild(h);for(var g=0;g<a.length;g++)h.removeChild(a[g]);for(g=0;g<b.length;g++)h.removeChild(b[g])};this._createPayouts=function(){a=[];b=[];for(var e=[{x:430,y:92},{x:630,y:92},{x:860,y:92},{x:1100,y:92},{x:430,y:195},{x:650,y:195},{x:870,y:195},{x:1100,y:195}],g=0,l=0;l<s_aSymbolWin.length;l++){for(var d=[],k=0;k<s_aSymbolWin[l].length;k++)d[k]=s_aSymbolWin[l][k];
do k=d.indexOf(0),-1!==k&&d.splice(k,1);while(-1!==k);k=d.length;if(0!==k){var n=30;4===k&&(n=22);var f=e[g].y;a[l]=[];b[l]=[];for(var q=0;q<k;q++){var t=new createjs.Text("X"+(5-q),"25px "+FONT_GAME,"#ffffff");t.textAlign="center";t.x=e[g].x;t.y=f;t.textBaseline="alphabetic";h.addChild(t);a[l][q]=t;var m=new createjs.Text(d[k-q-1],"25px "+FONT_GAME,"#ffff00");m.textAlign="center";m.x=t.x+50;m.y=t.y;m.textBaseline="alphabetic";h.addChild(m);b[l][q]=m;f+=n}g++}}};this.show=function(){h.visible=!0};
this.hide=function(){h.visible=!1};this.resetHighlightCombo=function(){for(var e=0;e<a.length;e++)for(var g=0;g<a[e].length;g++)a[e][g].color="#ffffff",b[e][g].color="#ffff00",createjs.Tween.removeTweens(b[e][g]),b[e][g].alpha=1};this.highlightCombo=function(a,e){a!==BONUS_SYMBOL&&(b[a-1][NUM_REELS-e].color="#ff0000",this.tweenAlpha(b[a-1][NUM_REELS-e],0))};this.tweenAlpha=function(a,b){var e=this;createjs.Tween.get(a).to({alpha:b},200).call(function(){1===b?e.tweenAlpha(a,0):e.tweenAlpha(a,1)})};
this._onExit=function(){s_oGame.hidePayTable()};this.isVisible=function(){return h.visible};this._init()}
function CStaticSymbolCell(a,b,g,e){var n=-1,h,r,p,l;this._init=function(a,b,e,f){l=new createjs.Container;l.visible=!1;r=[];for(a=0;a<NUM_SYMBOLS;a++)b=createSprite(s_aSymbolAnims[a],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE),b.stop(),b.x=e,b.y=f,b.on("animationend",this._onAnimEnded,null,!1,{index:a}),l.addChild(b),r[a]=b,r[a].visible=!1;a={framerate:60,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
19]}};a=new createjs.SpriteSheet(a);p=new createSprite(a,"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);p.stop();p.x=e;p.y=f;l.addChild(p);s_oStage.addChild(l)};this.unload=function(){s_oStage.removeChild(l)};this.hide=function(){-1<n&&(p.gotoAndStop("static"),p.visible=!1,r[n].gotoAndPlay("static"),l.visible=!1)};this.show=function(a){p.gotoAndPlay("anim");p.visible=!0;for(var b=0;b<NUM_SYMBOLS;b++)r[b].visible=b+1===a?!0:!1;r[a-1].gotoAndPlay("anim");n=a-1;h=r[a-1].spriteSheet.getNumFrames();l.visible=!0};
this._onAnimEnded=function(a,b){r[b.index].currentFrame!==h&&(r[b.index].stop(),setTimeout(function(){r[b.index].gotoAndPlay(1)},100))};this.stopAnim=function(){r[n].gotoAndStop("static");r[n].visible=!1;p.gotoAndStop("static");p.visible=!1};this._init(a,b,g,e)}
function CTweenController(){this.tweenValue=function(a,b,g){return a+g*(b-a)};this.easeLinear=function(a,b,g,e){return g*a/e+b};this.easeInCubic=function(a,b,g,e){e=(a/=e)*a*a;return b+g*e};this.easeBackInQuart=function(a,b,g,e){e=(a/=e)*a;return b+g*(2*e*e+2*e*a+-3*e)};this.easeInBack=function(a,b,g,e){return g*(a/=e)*a*(2.70158*a-1.70158)+b};this.easeOutCubic=function(a,b,g,e){return g*((a=a/e-1)*a*a+1)+b}}
function CBonusPanel(){var a,b,g,e,n,h,r,p,l,d;this._init=function(){d=new createjs.Container;s_oStage.addChild(d);var a=createBitmap(s_oSpriteLibrary.getSprite("bonus_bg"));d.alpha=0;d.visible=!1;d.addChild(a);a={framerate:3,images:[s_oSpriteLibrary.getSprite("chicken")],frames:{width:CHICKEN_WIDTH,height:CHICKEN_HEIGHT,regX:CHICKEN_WIDTH/2,regY:CHICKEN_HEIGHT/2},animations:{idle:[0,5,"idle"],lay_egg:[6,9,"lay_egg"],idle_rand_0:[1,5,"idle"],idle_rand_1:[2,5,"idle"],idle_rand_2:[3,5,"idle"],idle_rand_3:[4,
5,"idle"],right:[3],left:[4]}};a=new createjs.SpriteSheet(a);e=[];for(var b=420,f=0;5>f;f++){var g=createSprite(a,"idle",CHICKEN_WIDTH/2,CHICKEN_HEIGHT/2,CHICKEN_WIDTH,CHICKEN_HEIGHT);g.on("click",this._onChickenReleased,this,!1,f);g.x=b;g.y=286;g.stop();g.visible=!1;d.addChild(g);b+=164;e[f]=g}b=s_oSpriteLibrary.getSprite("egg");a={framerate:10,images:[b],frames:{width:Math.floor(b.width/NUM_PRIZES),height:b.height,regX:Math.floor(b.width/NUM_PRIZES)/2,regY:b.height/2},animations:{egg_0:[0],egg_1:[1],
egg_2:[2]}};a=new createjs.SpriteSheet(a);p=createSprite(a,"egg_0",Math.floor(b.width/NUM_PRIZES)/2,b.height/2,Math.floor(b.width/NUM_PRIZES),b.height);d.addChild(p);f=new createjs.Shape;f.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(110,390,800,160);d.addChild(f);p.mask=f;h=[];r=[];h[0]=createSprite(a,"egg_0",Math.floor(b.width/NUM_PRIZES)/2,b.height/2,Math.floor(b.width/NUM_PRIZES),b.height);h[0].x=350;h[0].y=CANVAS_HEIGHT-70;d.addChild(h[0]);f=new createjs.Text("100","34px "+FONT_GAME,"#ffff00");
f.textAlign="left";f.x=h[0].x+b.width/NUM_PRIZES/2+6;f.y=h[0].y+12;f.textBaseline="alphabetic";d.addChild(f);r.push(f);h[1]=createSprite(a,"egg_1",Math.floor(b.width/NUM_PRIZES)/2,b.height/2,Math.floor(b.width/NUM_PRIZES),b.height);h[1].x=650;h[1].y=CANVAS_HEIGHT-70;d.addChild(h[1]);f=new createjs.Text("200","34px "+FONT_GAME,"#ffff00");f.textAlign="left";f.x=h[1].x+ +(b.width/NUM_PRIZES)/2+6;f.y=h[1].y+12;f.textBaseline="alphabetic";d.addChild(f);r.push(f);h[2]=createSprite(a,"egg_2",Math.floor(b.width/
NUM_PRIZES)/2,b.height/2,Math.floor(b.width/NUM_PRIZES),b.height);h[2].x=950;h[2].y=CANVAS_HEIGHT-70;d.addChild(h[2]);f=new createjs.Text("300","34px "+FONT_GAME,"#ffff00");f.textAlign="left";f.x=h[2].x+ +(b.width/NUM_PRIZES)/2+6;f.y=h[2].y+12;f.textBaseline="alphabetic";d.addChild(f);r.push(f);l=new createjs.Text("X 300$","80px "+FONT_GAME,"#ffff00");l.alpha=0;l.textAlign="center";l.shadow=new createjs.Shadow("#000",2,2,2);l.x=CANVAS_WIDTH/2;l.y=150;l.textBaseline="alphabetic";d.addChild(l)};this.unload=
function(){for(var a=0;5>a;a++)e[a].off("click",this._onChickenReleased)};this.show=function(b,h){$(s_oMain).trigger("bonus_start");g=h;a=!1;l.alpha=0;switch(b){case 3:n=BONUS_PRIZE[0];break;case 4:n=BONUS_PRIZE[1];break;case 5:n=BONUS_PRIZE[2];break;default:n=BONUS_PRIZE[0]}r[0].text="X"+n[0];r[1].text="X"+n[1];r[2].text="X"+n[2];p.x=118;p.y=308;p.rotation=0;p.gotoAndStop("egg_0");for(var f=0;f<b;f++){var k=Math.floor(4*Math.random());e[f].framerate=3;e[f].visible=!0;e[f].gotoAndPlay("idle_rand_"+
k)}d.visible=!0;createjs.Tween.get(d).to({alpha:1},1E3);setVolume("soundtrack",0);playSound("soundtrack_bonus",1,!0)};this._onChickenReleased=function(b,d){if(!a){a=!0;do var e=Math.floor(Math.random()*s_aEggOccurence.length);while(n[s_aEggOccurence[e]]*g>SLOT_CASH);this.playChickenLayAnim(d,s_aEggOccurence[e]);playSound("choose_chicken",1,!1)}};this.playChickenLayAnim=function(a,d){b=n[d];p.gotoAndStop("egg_"+d);for(var f=0;5>f;f++)f<a?e[f].gotoAndStop("right"):f===a?(e[a].framerate=10,e[a].gotoAndPlay("lay_egg")):
e[f].gotoAndStop("left");var g=this;setTimeout(function(){g.layEgg(a)},2500)};this.layEgg=function(a){e[a].gotoAndStop(5);p.x=e[a].x;var b=this;createjs.Tween.get(p).to({y:460},300).call(function(){b.endBonus()});playSound("reveal_egg",1,!1)};this.endBonus=function(){l.text="X "+b;createjs.Tween.get(l).to({alpha:1},500);createjs.Tween.get(p).to({rotation:110},500);setTimeout(function(){d.alpha=0;d.visible=!1;for(var a=0;a<e.length;a++)e[a].visible=!1;setVolume("soundtrack",SOUNDTRACK_VOLUME);stopSound("soundtrack_bonus");
s_oGame.endBonus(b)},4E3)};this._init()}
function CCreditsPanel(){var a,b,g,e,n,h,r,p,l,d;this._init=function(){d=new createjs.Container;d.alpha=0;s_oStage.addChild(d);var k=new createjs.Shape;k.graphics.beginFill("rgba(0,0,0,0.7)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.addChild(k);b=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d.addChild(b);r=new createjs.Shape;r.graphics.beginFill("#0f0f0f").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.alpha=.01;r.on("click",this._onLogoButRelease);d.addChild(r);k=s_oSpriteLibrary.getSprite("but_exit");
a=CANVAS_WIDTH/2+245;e=new CGfxButton(a,155,k,d);e.addEventListener(ON_MOUSE_UP,this.unload,this);h=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+FONT_GAME,"#000");h.textAlign="center";h.textBaseline="alphabetic";h.x=CANVAS_WIDTH/2;h.y=270;h.outline=2;d.addChild(h);n=new createjs.Text(TEXT_CREDITS_DEVELOPED,"40px "+FONT_GAME,"#fff");n.textAlign="center";n.textBaseline="alphabetic";n.x=CANVAS_WIDTH/2;n.y=270;d.addChild(n);k=s_oSpriteLibrary.getSprite("logo_ctl");g=createBitmap(k);g.regX=k.width/
2;g.regY=k.height/2;g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2;d.addChild(g);l=new createjs.Text("www.codethislab.com","34px "+FONT_GAME,"#000");l.textAlign="center";l.textBaseline="alphabetic";l.x=CANVAS_WIDTH/2;l.y=395;l.outline=2;d.addChild(l);p=new createjs.Text("www.codethislab.com","34px "+FONT_GAME,"#fff");p.textAlign="center";p.textBaseline="alphabetic";p.x=CANVAS_WIDTH/2;p.y=395;d.addChild(p);createjs.Tween.get(d).to({alpha:1},600,createjs.Ease.cubicOut);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};
this.refreshButtonPos=function(a,b){};this.unload=function(){r.off("click",this._onLogoButRelease);e.unload();e=null;s_oStage.removeChild(d)};this._onLogoButRelease=function(){window.open("http://www.codethislab.com/index.php?&l=en","_blank")};this._init()};